#include <limits.h>
#include <net/if.h>

/* defines to compile only necessary functions */
#define LOGFILE_AND_INFLUXDB 0
#define LOGFILE 1
#define INFLUXDB 2

#ifdef ENABLE_OUTPUT
#  if ENABLE_OUTPUT == LOGFILE_AND_INFLUXDB
#    define IOTRACE_ENABLE_LOGFILE
#    define IOTRACE_ENABLE_INFLUXDB
#  elif ENABLE_OUTPUT == LOGFILE
#    define IOTRACE_ENABLE_LOGFILE
#    undef IOTRACE_ENABLE_INFLUXDB
#  elif ENABLE_OUTPUT == INFLUXDB
#    undef IOTRACE_ENABLE_LOGFILE
#    define IOTRACE_ENABLE_INFLUXDB
#  endif
#endif

#include "libiotrace_defines.h"

#ifdef LIBIOTRACE_STRUCT

#define MAXFILENAME PATH_MAX /* get length filename from limits.h */
#ifndef MAX_ERROR_TEXT
#  define MAX_ERROR_TEXT 1024
#endif
#ifndef MAX_FUNCTION_NAME
#  define MAX_FUNCTION_NAME 40
#endif
#ifndef MAX_MSG_FILE_DESCRIPTORS
#  define MAX_MSG_FILE_DESCRIPTORS 200 // TODO: use SCM_MAX_FD instead
#endif

#ifndef MAX_STACKTRACE_DEPTH
#  define MAX_STACKTRACE_DEPTH 50
#endif
#ifndef MAX_STACKTRACE_ENTRY_LENGTH
#  define MAX_STACKTRACE_ENTRY_LENGTH 200
#endif

#define MAX_SOCKADDR_LENGTH ((sizeof(struct sockaddr_storage) >= sizeof(struct sockaddr_un) ? \
                              sizeof(struct sockaddr_storage) : sizeof(struct sockaddr_un)) \
                             - sizeof(sa_family_t))

LIBIOTRACE_STRUCT_START(file_stream)
  LIBIOTRACE_STRUCT_FILE_P(stream)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(file_dir)
  LIBIOTRACE_STRUCT_VOID_P(directory_stream)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(file_descriptor)
  LIBIOTRACE_STRUCT_INT(descriptor)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(file_memory)
  LIBIOTRACE_STRUCT_VOID_P(address)
  LIBIOTRACE_STRUCT_SIZE_T(length)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(file_async)
  LIBIOTRACE_STRUCT_VOID_P_CONST(async)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(file_mpi)
  LIBIOTRACE_STRUCT_INT(mpi_file)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(request_mpi)
  LIBIOTRACE_STRUCT_INT(request_id)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(shared_library)
  LIBIOTRACE_STRUCT_VOID_P_CONST(dl_handle)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(file_alloc)
  LIBIOTRACE_STRUCT_VOID_P(address)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(errno_detail)
  LIBIOTRACE_STRUCT_INT(errno_value)
  LIBIOTRACE_STRUCT_CSTRING_P(errno_text, MAX_ERROR_TEXT)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ENUM_START(access_mode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(read_only)      //O_RDONLY or r
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(write_only)     //O_WRONLY or w, a
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(read_and_write) //O_RDWR or r+, w+, a+
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_access_mode)
LIBIOTRACE_STRUCT_ENUM_END

// ToDo: check if all possible flags for each BITFIELD are covered

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(creation_flags)
#ifdef HAVE_O_CLOEXEC
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(cloexec)
#endif
#ifdef HAVE_O_DIRECTORY
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory)
#endif
#ifdef HAVE_O_NOFOLLOW
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(nofollow)
#endif
#ifdef HAVE_O_TMPFILE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(tmpfile)
#endif
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(creat)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(excl)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(noctty)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(trunc)
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(status_flags)
#ifdef HAVE_O_DIRECT
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(direct)
#endif
#ifdef HAVE_O_NOATIME
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(noatime)
#endif
#ifdef HAVE_O_PATH
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(path)
#endif
#ifdef HAVE_O_LARGEFILE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(largefile)
#endif
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(append)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(initial_append)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(async)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(dsync)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(nonblock)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(ndelay)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(sync)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(delete_on_close)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(unique_open)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(sequential)
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(mode_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(read_by_owner)     //S_IRUSR
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(write_by_owner)    //S_IWUSR
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(execute_by_owner)  //S_IXUSR
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(read_by_group)     //S_IRGRP
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(write_by_group)    //S_IWGRP
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(execute_by_group)  //S_IXGRP
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(read_by_others)    //S_IROTH
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(write_by_others)   //S_IWOTH
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(execute_by_others) //S_IXOTH
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(rwf_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(hipri)  //RWF_HIPRI
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(dsync)  //RWF_DSYNC
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(sync)   //RWF_SYNC
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(nowait) //RWF_NOWAIT
#ifdef HAVE_RWF_APPEND
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(append) //RWF_APPEND
#endif
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(memory_map_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(shared)        //MAP_SHARED
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(private)       //MAP_PRIVATE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(fixed)         //MAP_FIXED
#ifdef HAVE_MAP_32BIT
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(bit32)         //MAP_32BIT
#endif
#ifdef HAVE_MAP_ANONYMOUS
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(anonymous)     //MAP_ANONYMOUS
#endif
#ifdef HAVE_MAP_DENYWRITE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(denywrite)     //MAP_DENYWRITE
#endif
#ifdef HAVE_MAP_EXECUTABLE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(executable)    //MAP_EXECUTABLE
#endif
#ifdef HAVE_MAP_FILE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(file)          //MAP_FILE
#endif
#ifdef HAVE_MAP_GROWSDOWN
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(growsdown)     //MAP_GROWSDOWN
#endif
#ifdef HAVE_MAP_HUGETLB
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(hugetlb)       //MAP_HUGETLB
#endif
#ifdef HAVE_MAP_HUGE_2MB
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(huge_2mb)      //MAP_HUGE_2MB
#endif
#ifdef HAVE_MAP_HUGE_1GB
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(huge_1gb)      //MAP_HUGE_1GB
#endif
#ifdef HAVE_MAP_LOCKED
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(locked)        //MAP_LOCKED
#endif
#ifdef HAVE_MAP_NONBLOCK
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(nonblock)      //MAP_NONBLOCK
#endif
#ifdef HAVE_MAP_NORESERVE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(noreserve)     //MAP_NORESERVE
#endif
#ifdef HAVE_MAP_POPULATE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(populate)      //MAP_POPULATE
#endif
#ifdef HAVE_MAP_STACK
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(stack)         //MAP_STACK
#endif
#ifdef HAVE_MAP_UNINITIALIZED
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(uninitialized) //MAP_UNINITIALIZED
#endif
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(memory_protection_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(executed) //PROT_EXEC
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(read)     //PROT_READ
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(written)  //PROT_WRITE
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(memory_sync_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(sync)       //MS_SYNC
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(async)      //MS_ASYNC
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(invalidate) //MS_INVALIDATE
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

#ifdef HAVE_MREMAP
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(memory_remap_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(maymove) //MREMAP_MAYMOVE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(fixed)   //MREMAP_FIXED
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END
#endif

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(dlopen_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(lazy_binding) //RTLD_LAZY
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(bind_now)     //RTLD_NOW
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(global)       //RTLD_GLOBAL
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(local)        //RTLD_LOCAL
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(no_delete)    //RTLD_NODELETE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(no_load)      //RTLD_NOLOAD
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(deep_bind)    //RTLD_DEEPBIND
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_ENUM_START(open_relative_to)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(file)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(current_working_dir)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(lock_mode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(internal)        //FSETLOCKING_INTERNAL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(bycaller)        //FSETLOCKING_BYCALLER
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(query_lock_mode) //FSETLOCKING_QUERY
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_lock_mode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(orientation_mode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(narrow)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(wide)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(not_set)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(query_orientation_mode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(read_write_state)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(ok)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(eof)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(error)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_read_write_state)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(seek_where)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(beginning_of_file)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(current_position)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(end_of_file)
#ifdef HAVE_SEEK_DATA
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(next_data)
#endif
#ifdef HAVE_SEEK_HOLE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(next_hole)
#endif
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_seek_where)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(buffer_mode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(fully_buffered)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(line_buffered)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unbuffered)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_buffer_mode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(madvice_advice)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(normal)         //MADV_NORMAL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(madvice_random) //MADV_RANDOM
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(sequential)     //MADV_SEQUENTIAL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(willneed)       //MADV_WILLNEED
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dontneed)       //MADV_DONTNEED
#ifdef HAVE_MADV_REMOVE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(madvice_remove) //MADV_REMOVE
#endif
#ifdef HAVE_MADV_DONTFORK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dontfork)       //MADV_DONTFORK
#endif
#ifdef HAVE_MADV_DOFORK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dofork)         //MADV_DOFORK
#endif
#ifdef HAVE_MADV_HWPOISON
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hwpoison)       //MADV_HWPOISON
#endif
#ifdef HAVE_MADV_MERGEABLE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(mergeable)      //MADV_MERGEABLE
#endif
#ifdef HAVE_MADV_UNMERGEABLE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unmergeable)    //MADV_UNMERGEABLE
#endif
#ifdef HAVE_MADV_SOFT_OFFLINE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(soft_offline)   //MADV_SOFT_OFFLINE
#endif
#ifdef HAVE_MADV_HUGEPAGE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hugepage)       //MADV_HUGEPAGE
#endif
#ifdef HAVE_MADV_NOHUGEPAGE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(nohugepage)     //MADV_NOHUGEPAGE
#endif
#ifdef HAVE_MADV_DONTDUMP
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dontdump)       //MADV_DONTDUMP
#endif
#ifdef HAVE_MADV_DODUMP
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dodump)         //MADV_DODUMP
#endif
#ifdef HAVE_MADV_FREE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(madvice_free)   //MADV_FREE
#endif
#ifdef HAVE_MADV_WIPEONFORK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(wipeonfork)     //MADV_WIPEONFORK
#endif
#ifdef HAVE_MADV_KEEPONFORK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(keeponfork)     //MADV_KEEPONFORK
#endif
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_madvice_advice)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(posix_madvice_advice)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(posix_normal)         //POSIX_MADV_NORMAL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(posix_madvice_random) //POSIX_MADV_RANDOM
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(posix_sequential)     //POSIX_MADV_SEQUENTIAL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(posix_willneed)       //POSIX_MADV_WILLNEED
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(posix_dontneed)       //POSIX_MADV_DONTNEED
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_posix_madvice_advice)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(listio_opcode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(lio_read)  //LIO_READ
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(lio_write) //LIO_WRITE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_listio_opcode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(listio_mode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(lio_wait)   //LIO_WAIT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(lio_nowait) //LIO_NOWAIT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_listio_mode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(async_state)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(inprogress) //EINPROGRESS
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(canceled)   //ECANCELED
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(completed)  //0
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(failed)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(async_sync_mode)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(like_fdatasync) //O_DSYNC
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(like_fsync)     //O_SYNC
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_async_sync_mode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ENUM_START(async_cancel_state)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(is_canceled)   //AIO_CANCELED
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(not_canceled)  //AIO_NOTCANCELED
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(allready_done) //AIO_ALLDONE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_async_cancel_state)
LIBIOTRACE_STRUCT_ENUM_END

#pragma push_macro("true")
#pragma push_macro("false")
#undef true
#undef false
LIBIOTRACE_STRUCT_ENUM_START(boolean)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(true)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(false)
LIBIOTRACE_STRUCT_ENUM_END
#pragma pop_macro("true")
#pragma pop_macro("false")

/* struct for timeval */
LIBIOTRACE_STRUCT_START(libiotrace_timeval)
  LIBIOTRACE_STRUCT_LONG_INT(sec)
  LIBIOTRACE_STRUCT_LONG_INT(micro_sec)
LIBIOTRACE_STRUCT_END

/* struct for timespec */
LIBIOTRACE_STRUCT_START(libiotrace_timespec)
  LIBIOTRACE_STRUCT_LONG_INT(sec)
  LIBIOTRACE_STRUCT_LONG_INT(nano_sec)
LIBIOTRACE_STRUCT_END

/* struct for file_id */
LIBIOTRACE_STRUCT_START(file_id)
  LIBIOTRACE_STRUCT_DEV_T(device_id)
  LIBIOTRACE_STRUCT_INO_T(inode_nr)
LIBIOTRACE_STRUCT_END

/* struct for file open */
LIBIOTRACE_STRUCT_START(open_function)
  LIBIOTRACE_STRUCT_ENUM(access_mode, mode)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(creation_flags, creation)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(status_flags, status)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(mode_flags, file_mode)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
  LIBIOTRACE_STRUCT_STRUCT(file_id, id)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(mpi_open_function)
  LIBIOTRACE_STRUCT_ENUM(access_mode, mode)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(creation_flags, creation)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(status_flags, status)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(mode_flags, file_mode)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
  LIBIOTRACE_STRUCT_STRUCT(file_id, id)
  LIBIOTRACE_STRUCT_KEY_VALUE_ARRAY(file_hints, MAX_MPI_FILE_HINTS, MAX_MPI_FILE_HINT_LENGTH)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(mpi_delete_function)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
  LIBIOTRACE_STRUCT_STRUCT(file_id, id)
  LIBIOTRACE_STRUCT_KEY_VALUE_ARRAY(file_hints, MAX_MPI_FILE_HINTS, MAX_MPI_FILE_HINT_LENGTH)
LIBIOTRACE_STRUCT_END

/* struct for file openat */
LIBIOTRACE_STRUCT_START(openat_function)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
  LIBIOTRACE_STRUCT_ENUM(access_mode, mode)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(creation_flags, creation)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(status_flags, status)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(mode_flags, file_mode)
  LIBIOTRACE_STRUCT_ENUM(open_relative_to, relative_to)
  LIBIOTRACE_STRUCT_INT(file_descriptor)
  LIBIOTRACE_STRUCT_STRUCT(file_id, id)
LIBIOTRACE_STRUCT_END

/* struct for file open descriptor as stream */
LIBIOTRACE_STRUCT_START(fdopen_function)
  LIBIOTRACE_STRUCT_INT(descriptor)
  LIBIOTRACE_STRUCT_ENUM(access_mode, mode)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(creation_flags, creation)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(status_flags, status)
LIBIOTRACE_STRUCT_END

/* struct for file information */
LIBIOTRACE_STRUCT_START(information_function)
  LIBIOTRACE_STRUCT_ENUM(boolean, return_bool)
LIBIOTRACE_STRUCT_END

/* struct for file lock_mode */
LIBIOTRACE_STRUCT_START(lock_mode_function)
  LIBIOTRACE_STRUCT_ENUM(lock_mode, set_mode)
  LIBIOTRACE_STRUCT_ENUM(lock_mode, return_mode)
LIBIOTRACE_STRUCT_END

/* struct for file orientation_mode */
LIBIOTRACE_STRUCT_START(orientation_mode_function)
  LIBIOTRACE_STRUCT_ENUM(orientation_mode, set_mode)
  LIBIOTRACE_STRUCT_ENUM(orientation_mode, return_mode)
LIBIOTRACE_STRUCT_END

/* struct for file write */
LIBIOTRACE_STRUCT_START(write_function)
  LIBIOTRACE_STRUCT_SIZE_T(written_bytes)
LIBIOTRACE_STRUCT_END

/* struct for file pwrite */
LIBIOTRACE_STRUCT_START(pwrite_function)
  LIBIOTRACE_STRUCT_SIZE_T(written_bytes)
  LIBIOTRACE_STRUCT_OFF_T(position)
LIBIOTRACE_STRUCT_END

/* struct for file pwrite2 */
LIBIOTRACE_STRUCT_START(pwrite2_function)
  LIBIOTRACE_STRUCT_SIZE_T(written_bytes)
  LIBIOTRACE_STRUCT_OFF_T(position)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(rwf_flags, flags)
LIBIOTRACE_STRUCT_END

/* struct for file read */
LIBIOTRACE_STRUCT_START(read_function)
  LIBIOTRACE_STRUCT_SIZE_T(read_bytes)
LIBIOTRACE_STRUCT_END

/* struct for file pread */
LIBIOTRACE_STRUCT_START(pread_function)
  LIBIOTRACE_STRUCT_SIZE_T(read_bytes)
  LIBIOTRACE_STRUCT_OFF_T(position)
LIBIOTRACE_STRUCT_END

/* struct for file pread2 */
LIBIOTRACE_STRUCT_START(pread2_function)
  LIBIOTRACE_STRUCT_SIZE_T(read_bytes)
  LIBIOTRACE_STRUCT_OFF_T(position)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(rwf_flags, flags)
LIBIOTRACE_STRUCT_END

/* struct for file copy read */
LIBIOTRACE_STRUCT_START(copy_read_function)
  LIBIOTRACE_STRUCT_SIZE_T(read_bytes)
  LIBIOTRACE_STRUCT_OFF_T(position)
  LIBIOTRACE_STRUCT_ENUM(seek_where, relative_to)
  LIBIOTRACE_STRUCT_INT(to_file_descriptor)
LIBIOTRACE_STRUCT_END

/* struct for file copy write */
LIBIOTRACE_STRUCT_START(copy_write_function)
  LIBIOTRACE_STRUCT_SIZE_T(written_bytes)
  LIBIOTRACE_STRUCT_OFF_T(position)
  LIBIOTRACE_STRUCT_ENUM(seek_where, relative_to)
  LIBIOTRACE_STRUCT_INT(from_file_descriptor)
LIBIOTRACE_STRUCT_END

/* struct for file unget */
LIBIOTRACE_STRUCT_START(unget_function)
  LIBIOTRACE_STRUCT_INT(buffer_bytes)
LIBIOTRACE_STRUCT_END

/* struct for file position */
LIBIOTRACE_STRUCT_START(position_function)
  LIBIOTRACE_STRUCT_OFF_T(position)
LIBIOTRACE_STRUCT_END

/* struct for file positioning */
LIBIOTRACE_STRUCT_START(positioning_function)
  LIBIOTRACE_STRUCT_ENUM(seek_where, relative_to)
  LIBIOTRACE_STRUCT_OFF_T(offset)
LIBIOTRACE_STRUCT_END

/* struct for file lpositioning */
LIBIOTRACE_STRUCT_START(lpositioning_function)
  LIBIOTRACE_STRUCT_ENUM(seek_where, relative_to)
  LIBIOTRACE_STRUCT_OFF_T(offset)
  LIBIOTRACE_STRUCT_OFF_T(new_offset_relative_to_beginning_of_file)
LIBIOTRACE_STRUCT_END

/* struct for file buffer */
LIBIOTRACE_STRUCT_START(buffer_function)
  LIBIOTRACE_STRUCT_ENUM(buffer_mode, buffer_mode)
  LIBIOTRACE_STRUCT_SIZE_T(buffer_size)
LIBIOTRACE_STRUCT_END

/* struct for fileno */
LIBIOTRACE_STRUCT_START(fileno_function)
  LIBIOTRACE_STRUCT_INT(file_descriptor)
LIBIOTRACE_STRUCT_END

/* struct for file bufsize */
LIBIOTRACE_STRUCT_START(bufsize_function)
  LIBIOTRACE_STRUCT_SIZE_T(buffer_size)
LIBIOTRACE_STRUCT_END

/* struct for memory map */
LIBIOTRACE_STRUCT_START(memory_map_function)
  LIBIOTRACE_STRUCT_VOID_P(address)
  LIBIOTRACE_STRUCT_SIZE_T(length)
  LIBIOTRACE_STRUCT_OFF_T(offset)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(memory_protection_flags, protection_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(memory_map_flags, map_flags)
LIBIOTRACE_STRUCT_END

/* struct for memory sync */
LIBIOTRACE_STRUCT_START(memory_sync_function)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(memory_sync_flags, sync_flags)
LIBIOTRACE_STRUCT_END

/* struct for memory remap */
#ifdef HAVE_MREMAP
LIBIOTRACE_STRUCT_START(memory_remap_function)
  LIBIOTRACE_STRUCT_VOID_P(new_address)
  LIBIOTRACE_STRUCT_SIZE_T(new_length)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(memory_remap_flags, remap_flags)
LIBIOTRACE_STRUCT_END
#endif

/* struct for memory madvise */
LIBIOTRACE_STRUCT_START(memory_madvise_function)
  LIBIOTRACE_STRUCT_ENUM(madvice_advice, advice)
LIBIOTRACE_STRUCT_END

/* struct for memory posix madvise */
LIBIOTRACE_STRUCT_START(memory_posix_madvise_function)
  LIBIOTRACE_STRUCT_ENUM(posix_madvice_advice, advice)
LIBIOTRACE_STRUCT_END

/* struct for file select */
LIBIOTRACE_STRUCT_START(select_function)
  LIBIOTRACE_STRUCT_STRUCT(libiotrace_timeval, timeout)
  LIBIOTRACE_STRUCT_FD_SET_P(files_waiting_for_read)
  LIBIOTRACE_STRUCT_FD_SET_P(files_waiting_for_write)
  LIBIOTRACE_STRUCT_FD_SET_P(files_waiting_for_except)
  LIBIOTRACE_STRUCT_FD_SET_P(files_ready_for_read)
  LIBIOTRACE_STRUCT_FD_SET_P(files_ready_for_write)
  LIBIOTRACE_STRUCT_FD_SET_P(files_ready_for_except)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous read */
LIBIOTRACE_STRUCT_START(asynchronous_read_function)
  LIBIOTRACE_STRUCT_VOID_P(async)
  LIBIOTRACE_STRUCT_SIZE_T(bytes_to_read)
  LIBIOTRACE_STRUCT_OFF_T(position)
  LIBIOTRACE_STRUCT_INT(lower_prio)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous write */
LIBIOTRACE_STRUCT_START(asynchronous_write_function)
  LIBIOTRACE_STRUCT_VOID_P(async)
  LIBIOTRACE_STRUCT_SIZE_T(bytes_to_write)
  LIBIOTRACE_STRUCT_OFF_T(position)
  LIBIOTRACE_STRUCT_INT(lower_prio)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous listio */
LIBIOTRACE_STRUCT_START(asynchronous_listio_function)
  LIBIOTRACE_STRUCT_ENUM(listio_mode, mode)
  LIBIOTRACE_STRUCT_ENUM(listio_opcode, opcode)
  LIBIOTRACE_STRUCT_VOID_P_START(request_data)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(request_data, asynchronous_read_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(request_data, asynchronous_write_function)
  LIBIOTRACE_STRUCT_VOID_P_END(request_data)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous error */
LIBIOTRACE_STRUCT_START(asynchronous_error_function)
  LIBIOTRACE_STRUCT_ENUM(async_state, state)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous return */
LIBIOTRACE_STRUCT_START(asynchronous_return_function)
  LIBIOTRACE_STRUCT_SSIZE_T(return_value)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous sync */
LIBIOTRACE_STRUCT_START(asynchronous_sync_function)
  LIBIOTRACE_STRUCT_ENUM(async_sync_mode, sync_mode)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous suspend */
LIBIOTRACE_STRUCT_START(asynchronous_suspend_function)
  LIBIOTRACE_STRUCT_STRUCT(libiotrace_timespec, timeout)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous cancel */
LIBIOTRACE_STRUCT_START(asynchronous_cancel_function)
  LIBIOTRACE_STRUCT_VOID_P_CONST(async)
  LIBIOTRACE_STRUCT_ENUM(async_cancel_state, state)
LIBIOTRACE_STRUCT_END

/* struct for file asynchronous init */
LIBIOTRACE_STRUCT_START(asynchronous_init_function)
  LIBIOTRACE_STRUCT_INT(max_threads)
  LIBIOTRACE_STRUCT_INT(max_simultaneous_requests)
  LIBIOTRACE_STRUCT_INT(seconds_idle_before_terminate)
LIBIOTRACE_STRUCT_END

/* struct for file dlopen */
LIBIOTRACE_STRUCT_START(dlopen_function)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(dlopen_flags, dl_flags)
  LIBIOTRACE_STRUCT_STRUCT(file_id, id)
LIBIOTRACE_STRUCT_END

#if defined(HAVE_DLMOPEN) && defined(WITH_DL_IO)
LIBIOTRACE_STRUCT_START(so_namespace_id)
  LIBIOTRACE_STRUCT_LMID_T(id)
LIBIOTRACE_STRUCT_END
#endif

LIBIOTRACE_STRUCT_ENUM_START(so_namespace_mode_enum)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(initial_namespace) //LM_ID_BASE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(new_namespace)     //LM_ID_NEWLM
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_so_namespace_mode)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_START(so_namespace_mode)
  LIBIOTRACE_STRUCT_ENUM(so_namespace_mode_enum, mode)
LIBIOTRACE_STRUCT_END

/* struct for file dlmopen */
#if defined(HAVE_DLMOPEN) && defined(WITH_DL_IO)
LIBIOTRACE_STRUCT_START(dlmopen_function)
  LIBIOTRACE_STRUCT_VOID_P_START(so_namespace)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(so_namespace, so_namespace_id)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(so_namespace, so_namespace_mode)
  LIBIOTRACE_STRUCT_VOID_P_END(so_namespace)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(dlopen_flags, dl_flags)
  LIBIOTRACE_STRUCT_STRUCT(file_id, id)
LIBIOTRACE_STRUCT_END
#endif

/* struct for dup */
LIBIOTRACE_STRUCT_START(dup_function)
  LIBIOTRACE_STRUCT_INT(new_descriptor)
LIBIOTRACE_STRUCT_END

/* struct for dup3 */
LIBIOTRACE_STRUCT_START(dup3_function)
  LIBIOTRACE_STRUCT_INT(new_descriptor)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(creation_flags, creation)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ENUM_START(fcntl_cmd)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dupfd)            //F_DUPFD
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(dupfd_cloexec)    //F_DUPFD_CLOEXEC
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getfd)            //F_GETFD
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setfd)            //F_SETFD
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getfl)            //F_GETFL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setfl)            //F_SETFL
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setlk)            //F_SETLK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setlkw)           //F_SETLKW
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getlk)            //F_GETLK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(ofd_setlk)        //F_OFD_SETLK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(ofd_setlkw)       //F_OFD_SETLKW
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(ofd_getlk)        //F_OFD_GETLK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getown)           //F_GETOWN
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setown)           //F_SETOWN
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getown_ex)        //F_GETOWN_EX
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setown_ex)        //F_SETOWN_EX
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getsig)           //F_GETSIG
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setsig)           //F_SETSIG
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setlease)         //F_SETLEASE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getlease)         //F_GETLEASE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(notify)           //F_NOTIFY
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(setpipe_sz)       //F_SETPIPE_SZ
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(getpipe_sz)       //F_GETPIPE_SZ
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(add_seals)        //F_ADD_SEALS
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(get_seals)        //F_GET_SEALS
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(get_rw_hint)      //F_GET_RW_HINT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(set_rw_hint)      //F_SET_RW_HINT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(get_file_rw_hint) //F_GET_FILE_RW_HINT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(set_file_rw_hint) //F_SET_FILE_RW_HINT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_fcntl_cmd)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(file_descriptor_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(cloexec) //FD_CLOEXEC
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_START(fcntl_fd_function)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(file_descriptor_flags, fd_flags)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(fcntl_fl_function)
  LIBIOTRACE_STRUCT_ENUM(access_mode, mode)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(creation_flags, creation)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(status_flags, status)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ENUM_START(lock_type)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(read_lock)  //F_RDLCK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(write_lock) //F_WRLCK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unlock)     //F_UNLCK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_lock_type)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_START(fcntl_flock)
  LIBIOTRACE_STRUCT_ENUM(lock_type, type)
  LIBIOTRACE_STRUCT_ENUM(seek_where, relative_to)
  LIBIOTRACE_STRUCT_OFF_T(start)
  LIBIOTRACE_STRUCT_OFF_T(len)
  LIBIOTRACE_STRUCT_PID_T(pid)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ENUM_START(owner_type)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(owner_thread)        //F_OWNER_TID
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(owner_process)       //F_OWNER_PID
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(owner_process_group) //F_OWNER_PGRP
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_owner_type)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_START(fcntl_own)
  LIBIOTRACE_STRUCT_ENUM(owner_type, type)
  LIBIOTRACE_STRUCT_PID_T(id)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(fcntl_sig)
  LIBIOTRACE_STRUCT_INT(signal)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ENUM_START(lease_type)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(read_lease)   //F_RDLCK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(write_lease)  //F_WRLCK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unlock_lease) //F_UNLCK
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_lease_type)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_START(fcntl_lease)
  LIBIOTRACE_STRUCT_ENUM(lease_type, type)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(directory_notify_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_access)    //DN_ACCESS
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_modify)    //DN_MODIFY
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_create)    //DN_CREATE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_delete)    //DN_DELETE
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_rename)    //DN_RENAME
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_attribute) //DN_ATTRIB
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(directory_multishot) //DN_MULTISHOT
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_START(fcntl_dnotify)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(directory_notify_flags, flags)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(fcntl_pipe_size)
  LIBIOTRACE_STRUCT_INT(bytes)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ARRAY_BITFIELD_START(seal_flags)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(seal_seal)   //F_SEAL_SEAL
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(seal_shrink) //F_SEAL_SHRINK
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(seal_grow)   //F_SEAL_GROW
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD_ELEMENT(seal_write)  //F_SEAL_WRITE
LIBIOTRACE_STRUCT_ARRAY_BITFIELD_END

LIBIOTRACE_STRUCT_START(fcntl_seal)
  LIBIOTRACE_STRUCT_ARRAY_BITFIELD(seal_flags, flags)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_ENUM_START(hint_write_life)
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hint_write_life_not_set) //RWH_WRITE_LIFE_NOT_SET
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hint_write_life_none)    //RWH_WRITE_LIFE_NONE
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hint_write_life_short)   //RWH_WRITE_LIFE_SHORT
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hint_write_life_medium)  //RWH_WRITE_LIFE_MEDIUM
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hint_write_life_long)    //RWH_WRITE_LIFE_LONG
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(hint_write_life_extreme) //RWH_WRITE_LIFE_EXTREME
  LIBIOTRACE_STRUCT_ENUM_ELEMENT(unknown_hint_write_life)
LIBIOTRACE_STRUCT_ENUM_END

LIBIOTRACE_STRUCT_START(fcntl_hint)
  LIBIOTRACE_STRUCT_ENUM(hint_write_life, hint)
LIBIOTRACE_STRUCT_END

/* struct for fcntl */
LIBIOTRACE_STRUCT_START(fcntl_function)
  LIBIOTRACE_STRUCT_ENUM(fcntl_cmd, cmd)
  LIBIOTRACE_STRUCT_VOID_P_START(cmd_data)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, dup_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_fd_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_fl_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_flock)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_own)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_sig)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_lease)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_dnotify)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_pipe_size)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_seal)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(cmd_data, fcntl_hint)
  LIBIOTRACE_STRUCT_VOID_P_END(cmd_data)
LIBIOTRACE_STRUCT_END

/* struct for file-pair functions (pipe, pipe2) */
LIBIOTRACE_STRUCT_START(file_pair)
  LIBIOTRACE_STRUCT_INT(descriptor1)
  LIBIOTRACE_STRUCT_INT(descriptor2)
LIBIOTRACE_STRUCT_END

/* struct for socketpair */
LIBIOTRACE_STRUCT_START(socketpair_function)
  LIBIOTRACE_STRUCT_ENUM(boolean, connection_based)
  LIBIOTRACE_STRUCT_INT(descriptor1)
  LIBIOTRACE_STRUCT_INT(descriptor2)
LIBIOTRACE_STRUCT_END

/* struct for socket */
LIBIOTRACE_STRUCT_START(socket_function)
  LIBIOTRACE_STRUCT_ENUM(boolean, connection_based)
LIBIOTRACE_STRUCT_END

/* struct for fork */
LIBIOTRACE_STRUCT_START(fork_function)
  LIBIOTRACE_STRUCT_PID_T(pid)
LIBIOTRACE_STRUCT_END

/* struct for readdir */
LIBIOTRACE_STRUCT_START(readdir_function)
  LIBIOTRACE_STRUCT_CSTRING_P_CONST(file_name, MAXFILENAME)
LIBIOTRACE_STRUCT_END

/* struct for dirfd */
LIBIOTRACE_STRUCT_START(dirfd_function)
  LIBIOTRACE_STRUCT_INT(descriptor)
LIBIOTRACE_STRUCT_END

/* struct for bind and connect */
LIBIOTRACE_STRUCT_START(sockaddr_function)
  LIBIOTRACE_STRUCT_SA_FAMILY_T(family)
  LIBIOTRACE_STRUCT_CSTRING_P(address, MAX_SOCKADDR_LENGTH * 2 + 1) // *2 for hex and +1 for terminating '\0'
LIBIOTRACE_STRUCT_END

/* struct for sendmsg and recvmsg */
LIBIOTRACE_STRUCT_START(msg_function)
  LIBIOTRACE_STRUCT_STRUCT_P(sockaddr_function, sockaddr)
  LIBIOTRACE_STRUCT_INT_ARRAY(descriptors, MAX_MSG_FILE_DESCRIPTORS)
LIBIOTRACE_STRUCT_END

/* struct for sendmmsg and recvmmsg */
LIBIOTRACE_STRUCT_START(mmsg_function)
  LIBIOTRACE_STRUCT_STRUCT_ARRAY(msg_function, messages, MAX_MMSG_MESSAGES)
LIBIOTRACE_STRUCT_END

/* struct for accept */
LIBIOTRACE_STRUCT_START(accept_function)
  LIBIOTRACE_STRUCT_INT(new_descriptor)
LIBIOTRACE_STRUCT_END

/* struct for dataype size */
LIBIOTRACE_STRUCT_START(mpi_immediate)
  LIBIOTRACE_STRUCT_INT(request_id)
LIBIOTRACE_STRUCT_END

/* struct for dataype size */
LIBIOTRACE_STRUCT_START(mpi_immediate_at)
  LIBIOTRACE_STRUCT_INT(request_id)
  LIBIOTRACE_STRUCT_OFF_T(position)
LIBIOTRACE_STRUCT_END

/* struct for dataype size */
LIBIOTRACE_STRUCT_START(mpi_wait)
  LIBIOTRACE_STRUCT_INT(count_bytes)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(mpi_waitall_element)
  LIBIOTRACE_STRUCT_INT(count_bytes)
  LIBIOTRACE_STRUCT_INT(request_id)
  LIBIOTRACE_STRUCT_ENUM(read_write_state, return_state)
  LIBIOTRACE_STRUCT_STRUCT_P(errno_detail, return_state_detail)
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(mpi_waitall)
  LIBIOTRACE_STRUCT_STRUCT_ARRAY(mpi_waitall_element, requests, MAX_MPI_IMESSAGES)
LIBIOTRACE_STRUCT_END

/* struct for alloc */
LIBIOTRACE_STRUCT_START(alloc_function)
  LIBIOTRACE_STRUCT_SIZE_T(size)
#if defined(HAVE_MALLOC_USABLE_SIZE) && defined(WITH_USABLE_SIZE)
  LIBIOTRACE_STRUCT_SIZE_T(_usable_size)
#endif
LIBIOTRACE_STRUCT_END

LIBIOTRACE_STRUCT_START(realloc_function)
  LIBIOTRACE_STRUCT_SIZE_T(size)
  LIBIOTRACE_STRUCT_VOID_P(ptr)
#if defined(HAVE_MALLOC_USABLE_SIZE) && defined(WITH_USABLE_SIZE)
  LIBIOTRACE_STRUCT_SIZE_T(_usable_size)
#endif
LIBIOTRACE_STRUCT_END

/* struct for additional wrapper informations */
#ifdef LOG_WRAPPER_TIME
LIBIOTRACE_STRUCT_START(wrapper_data)
  LIBIOTRACE_STRUCT_U_INT64_T(time_start)
  LIBIOTRACE_STRUCT_U_INT64_T(time_end)
LIBIOTRACE_STRUCT_END
#endif

/* basic struct for every call */
LIBIOTRACE_STRUCT_START(basic)
#ifdef FILENAME_RESOLUTION_ENABLED
  LIBIOTRACE_STRUCT_CSTRING(traced_filename, FILENAME_MAX)
#endif
  LIBIOTRACE_STRUCT_CSTRING_P(hostname, HOST_NAME_MAX)
  LIBIOTRACE_STRUCT_PID_T(pid)
  LIBIOTRACE_STRUCT_PID_T(tid)
  // ToDo: function_name as CSTRING_P ?
  LIBIOTRACE_STRUCT_CSTRING(function_name, MAX_FUNCTION_NAME)
  LIBIOTRACE_STRUCT_U_INT64_T(time_start)
  LIBIOTRACE_STRUCT_U_INT64_T(time_end)
#ifdef IOTRACE_ENABLE_INFLUXDB
  LIBIOTRACE_STRUCT_U_INT64_T(time_diff)
#endif
  LIBIOTRACE_STRUCT_ENUM(read_write_state, return_state)
  LIBIOTRACE_STRUCT_STRUCT_P(errno_detail, return_state_detail)
  LIBIOTRACE_STRUCT_MALLOC_STRING_ARRAY(stacktrace_symbols, MAX_STACKTRACE_DEPTH, MAX_STACKTRACE_ENTRY_LENGTH)
  LIBIOTRACE_STRUCT_MALLOC_PTR_ARRAY(stacktrace_pointer, MAX_STACKTRACE_DEPTH)
#ifdef LOG_WRAPPER_TIME
  LIBIOTRACE_STRUCT_STRUCT(wrapper_data, wrapper)
#endif
  LIBIOTRACE_STRUCT_VOID_P_START(file_type)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_stream)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_dir)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_descriptor)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_memory)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_async)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_mpi)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, shared_library)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, request_mpi)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(file_type, file_alloc)
  LIBIOTRACE_STRUCT_VOID_P_END(file_type)
  // ToDo: new field for boolean which shows if file position has changed (e.g. copy_file_range don't change file position)
  // or corrupted (e.g. async functions)
  LIBIOTRACE_STRUCT_VOID_P_START(function_data)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, fork_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, open_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, openat_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, fdopen_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, information_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, lock_mode_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, orientation_mode_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, write_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, pwrite_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, pwrite2_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, read_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, pread_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, pread2_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, copy_read_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, copy_write_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, unget_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, position_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, positioning_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, lpositioning_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, buffer_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, fileno_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, bufsize_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, memory_map_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, memory_sync_function)
#ifdef HAVE_MREMAP
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, memory_remap_function)
#endif
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, memory_madvise_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, select_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, memory_posix_madvise_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_read_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_write_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_listio_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_error_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_return_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_sync_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_suspend_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_cancel_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, asynchronous_init_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, dlopen_function)
#if defined(HAVE_DLMOPEN) && defined(WITH_DL_IO)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, dlmopen_function)
#endif
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, dup_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, dup3_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, fcntl_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, file_pair)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, readdir_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, dirfd_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, msg_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mmsg_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, sockaddr_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, accept_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, socketpair_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, socket_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mpi_open_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mpi_immediate)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mpi_wait)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mpi_delete_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mpi_immediate_at)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, mpi_waitall)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, alloc_function)
    LIBIOTRACE_STRUCT_VOID_P_ELEMENT(function_data, realloc_function)
  LIBIOTRACE_STRUCT_VOID_P_END(function_data)
LIBIOTRACE_STRUCT_END

/* filesystem description */
LIBIOTRACE_STRUCT_START(filesystem)
  LIBIOTRACE_STRUCT_DEV_T(device_id)
  LIBIOTRACE_STRUCT_CSTRING_P(name, MAXFILENAME)
  LIBIOTRACE_STRUCT_CSTRING_P(path_prefix, MAXFILENAME)
  LIBIOTRACE_STRUCT_CSTRING_P(mount_type, MAXFILENAME)
  LIBIOTRACE_STRUCT_CSTRING_P(mount_options, MAXFILENAME)
  LIBIOTRACE_STRUCT_INT(dump_frequency_in_days)
  LIBIOTRACE_STRUCT_INT(pass_number_on_parallel_fsck)
LIBIOTRACE_STRUCT_END

/* working dir */
LIBIOTRACE_STRUCT_START(working_dir)
  LIBIOTRACE_STRUCT_U_INT64_T(time)
  LIBIOTRACE_STRUCT_CSTRING_P(hostname, HOST_NAME_MAX)
  LIBIOTRACE_STRUCT_PID_T(pid)
  LIBIOTRACE_STRUCT_CSTRING_P(dir, MAXFILENAME)
LIBIOTRACE_STRUCT_END

/* boolean for each wrapper (active/inactive) */
LIBIOTRACE_STRUCT_START(wrapper_status)
#undef WRAPPER_NAME_TO_SOURCE
#define WRAPPER_NAME_TO_SOURCE WRAPPER_NAME_TO_LIBIOTRACE_STRUCT
#include "event_wrapper.h"
#include "event_sim_wrapper.h"
#ifdef WITH_POSIX_IO
#  include "posix_io_wrapper.h"
#endif
#ifdef WITH_POSIX_AIO
#  include "posix_aio_wrapper.h"
#endif
#ifdef WITH_DL_IO
#  include "dl_io_wrapper.h"
#endif
#ifdef WITH_MPI_IO
#  include "mpi_io_wrapper.h"
#endif
#ifdef WITH_ALLOC
#  include "alloc_wrapper.h"
#endif
LIBIOTRACE_STRUCT_END

#if defined(IOTRACE_ENABLE_INFLUXDB) && defined(ENABLE_REMOTE_CONTROL)
/* influx meta data */
LIBIOTRACE_STRUCT_START(influx_meta)
  LIBIOTRACE_STRUCT_CSTRING_P(ip, 39)
  LIBIOTRACE_STRUCT_INT(port)
  LIBIOTRACE_STRUCT_STRUCT_P(wrapper_status, wrapper)
LIBIOTRACE_STRUCT_END
#endif

#if defined(ENABLE_REMOTE_CONTROL) && defined(IOTRACE_ENABLE_LOGFILE)
/* control commands meta data*/
LIBIOTRACE_STRUCT_START(control_meta)
  LIBIOTRACE_STRUCT_PID_T(pid)
  LIBIOTRACE_STRUCT_CSTRING_P(interface_name, IFNAMSIZ)
  LIBIOTRACE_STRUCT_CSTRING_P(ip, 39)
  LIBIOTRACE_STRUCT_INT(port)
LIBIOTRACE_STRUCT_END
#endif

#endif
