#include "wrapper_name.h"

WRAPPER_NAME(MPI_File_open)
WRAPPER_NAME(MPI_File_write)
WRAPPER_NAME(MPI_File_iwrite)
WRAPPER_NAME(MPI_File_iwrite_all)
WRAPPER_NAME(MPI_File_write_all)
WRAPPER_NAME(MPI_File_read)
WRAPPER_NAME(MPI_File_iread)
WRAPPER_NAME(MPI_File_iread_all)
WRAPPER_NAME(MPI_File_read_all)
WRAPPER_NAME(MPI_File_close)
WRAPPER_NAME(MPI_File_seek)
WRAPPER_NAME(MPI_File_write_at)
WRAPPER_NAME(MPI_File_write_at_all)
WRAPPER_NAME(MPI_File_read_at)
WRAPPER_NAME(MPI_File_read_at_all)
WRAPPER_NAME(MPI_File_iread_at)
WRAPPER_NAME(MPI_File_iread_at_all)
WRAPPER_NAME(MPI_File_iwrite_at)
WRAPPER_NAME(MPI_File_iwrite_at_all)
WRAPPER_NAME(MPI_File_read_all_begin)
WRAPPER_NAME(MPI_Wait)
WRAPPER_NAME(MPI_Waitall)
WRAPPER_NAME(MPI_File_delete)
WRAPPER_NAME(MPI_File_set_view)
WRAPPER_NAME(MPI_File_get_position)
