# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: InfluxDB
  # <string, required> datasource type. Required
  type: influxdb
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://influxdb:8086
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: true
  # <string> basic auth username
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  secureJsonData:
      token: "OXBWllU1poZotgyBlLlo2XQ_u4AYGYKQmdxvJJeotKRyvdn5mwjEhCXyOjyldpMmNt_9YY4k3CK-f5Eh1bN0Ng=="
  jsonData:
     defaultBucket: "hsebucket"
     httpMode: "POST"
     organization: "hse"
     version: "Flux"
  # <string> json object of data that will be encrypted.
readOnly: false
