version: '3'
services:
        grafana:
                image: 'grafana/grafana'
                ports:
                        - "3000:3000"
                depends_on:
                        - influxdb
                volumes:
                        - ./provisioning:/etc/grafana/provisioning
                        - ./config/grafana.ini:/etc/grafana/grafana.ini
   

        influxdb:
                image: quay.io/influxdb/influxdb:v2.0.3
                ports:
                        - "8086:8086"
                volumes:
                        - './influxdb:/var/lib/influxdb'
        influxdb_cli:
                links:
                        - influxdb
                image: quay.io/influxdb/influxdb:v2.0.3
# Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
                entrypoint: influx setup --bucket hsebucket -o hse --username=admin --password=test12345678 --host=http://influxdb:8086 -f
      # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service. 
                restart: on-failure:10
                depends_on:
                        - influxdb
