version: '3'
services:
        grafana:
                image: 'grafana/grafana'
                ports:
                        - "3000:3000"
                depends_on:
                        - prometheus
                volumes:
                        - ./provisioning:/etc/grafana/provisioning
   

        influxdb:
                image: quay.io/influxdb/influxdb:v2.0.2
                ports:
                        - "8086:8086"
                volumes:
                        - './influxdb:/var/lib/influxdb'
                environment: 
                        - INFLUXDB_DB=libiotrace
                        - INFLUXDB_ADMIN_USER=admin
                        - INFLUXDB_ADMIN_PASSWORD=test12345678
                        - INFLUXDB_HTTP_AUTH_ENABLED=true