{
 "title": "iotrace OpenFOAM",
 "time": { "from": "2001-01-01T03:14:22.011Z", "to": "2001-01-01T03:15:57.996Z" },
 "templating": {
  "list": [
   { "name": "data_collection", "label": "Data collection", "query": "SELECT name\nFROM collections" }
  ]
 },
 "panels": [
  {
   "title": "OpenFOAM wedge15Ma5 test 101: time for File I/O in ns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    TIMESTAMP(MAKEDATE(0001, 1), SEC_TO_TIME(functions.start_time / 1000000000)) AS time, -- grafana needs time series\n    functions.type AS metric,\n    CAST(SUM(functions.time) AS DECIMAL(20,0)) AS value -- grafana interprets long as string but needs numeric value as value\nFROM functions\nINNER JOIN function_manipulates_file\n    ON functions.collection_id = function_manipulates_file.collection_id\n        AND functions.id = function_manipulates_file.function_id\nINNER JOIN files\n    ON function_manipulates_file.collection_id = files.collection_id\n        AND function_manipulates_file.file = files.file\nWHERE functions.collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\n    AND files.kind = \"FILE\"\nGROUP BY TIMESTAMP(MAKEDATE(0001, 1), SEC_TO_TIME(functions.start_time / 1000000000)), type\n-- ORDER BY metric"
    }
   ]
  },
  {
   "title": "OpenFOAM wedge15Ma5 test 101: bytes for File I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    TIMESTAMP(MAKEDATE(0001, 1), SEC_TO_TIME(functions.start_time / 1000000000)) AS time, -- grafana needs time series\n    functions.type AS metric,\n    CAST(SUM(functions.bytes) AS DECIMAL(20,0)) AS value -- grafana interprets long as string but needs numeric value as value\nFROM functions\nINNER JOIN function_manipulates_file\n    ON functions.collection_id = function_manipulates_file.collection_id\n        AND functions.id = function_manipulates_file.function_id\nINNER JOIN files\n    ON function_manipulates_file.collection_id = files.collection_id\n        AND function_manipulates_file.file = files.file\nWHERE functions.collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\n    AND files.kind = \"FILE\"\nGROUP BY TIMESTAMP(MAKEDATE(0001, 1), SEC_TO_TIME(functions.start_time / 1000000000)), type\n-- ORDER BY metric"
    }
   ]
  },
  {
   "title": "OpenFOAM wedge15Ma5 test 101: bytes per function",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "targets": [
    {
     "rawSql": "SELECT\n    NOW() AS time,\n    name AS metric,\n    SUM(bytes) AS bytes\n--    SUM(time) AS ns\nFROM functions\nWHERE collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\nGROUP BY name\nHAVING SUM(bytes) > 0"
    }
   ]
  },
  {
   "title": "OpenFOAM wedge15Ma5 test 101: time per function",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "targets": [
    {
     "rawSql": "SELECT\n    NOW() AS time,\n    name AS metric,\n    SUM(time) AS ns\nFROM functions\nWHERE collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\nGROUP BY name\nHAVING SUM(time) > 0"
    }
   ]
  },
  {
   "title": "OpenFOAM wedge15Ma5 test 101: log(time) per function",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n--    NOW() AS time,\n    name AS metric,\n    LOG(SUM(time)) AS ns\nFROM functions\nWHERE collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\nGROUP BY name\n-- HAVING SUM(time) > 0"
    }
   ]
  },
  {
   "title": "OpenFOAM wedge15Ma5 test 101: log(bytes) per function",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    NOW() AS time,\n    name AS metric,\n    LOG(SUM(bytes)) AS bytes\nFROM functions\nWHERE collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\nGROUP BY name"
    }
   ]
  },
  {
   "title": "OpenFOAM wedge15Ma5 test 101: bytes for File I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    TIMESTAMP(MAKEDATE(0001, 1), SEC_TO_TIME(functions.start_time / 1000000000)) AS time, -- grafana needs time series\n    functions.type AS metric,\n    CAST(SUM(functions.bytes) AS DECIMAL(20,0)) AS value -- grafana interprets long as string but needs numeric value as value\nFROM functions\nINNER JOIN function_manipulates_file\n    ON functions.collection_id = function_manipulates_file.collection_id\n        AND functions.id = function_manipulates_file.function_id\nINNER JOIN files\n    ON function_manipulates_file.collection_id = files.collection_id\n        AND function_manipulates_file.file = files.file\nWHERE functions.collection_id = (SELECT id FROM collections WHERE name = \"2020-08-13_10:07:42_MESZ_openFOAM_wedge15Ma5_test101\")\n    AND files.kind = \"FILE\"\nGROUP BY TIMESTAMP(MAKEDATE(0001, 1), SEC_TO_TIME(functions.start_time / 1000000000)), type\n-- ORDER BY metric"
    }
   ]
  }
 ]
}