#!/bin/bash


DBNODE=$(scontrol show hostname | tail -n 1)
echo $DBNODE

export PATH="$PWD:$PATH"

tmux new-session -d -s "runsondbnode" srun -N 1 -n 1 -w $DBNODE --pty /bin/bash -c "export PATH="$PWD:$PATH" && runsondbnode"
#srun -n120 -l --multi-prog multiprog.conf

echo "Fertig"

sleep 30
while IFS= read -r line; do
    IB0ADDR=$line
done < ~/Projects/scripts/ib0

echo $IB0ADDR

cd $PWD && ./mpi_file_io.sh $IB0ADDR

#sleep 20000000

# export OMP_NUM_THREADS=$((${SLURM_CPUS_PER_TASK}/2))
# export MPIRUN_OPTIONS="-binding "domain=omp:compact" -print-rank-map -envall"
# export NUM_PROCS=eval(${SLURM_NTASKS}*${OMP_NUM_THREADS})
# echo "${EXE} running on ${NUM_PROCS} cores with ${SLURM_NTASKS} MPI-tasks and ${OMP_NUM_THREADS} threads"
# startexe="mpiexec.hydra -bootstrap slurm ${MPIRUN_OPTIONS} -n ${SLURM_NTASKS} ${EXE}"
# echo $startexe
# exec $startexe
