#!/bin/bash
rm -f /opt/.influx_cache/configs

export IOTRACE_INFLUX_ORGANIZATION=hse
export IOTRACE_INFLUX_BUCKET=hsebucket
export IOTRACE_INFLUX_TOKEN=OXBWllU1poZotgyBlLlo2XQ_u4AYGYKQmdxvJJeotKRyvdn5mwjEhCXyOjyldpMmNt_9YY4k3CK-f5Eh1bN0Ng==
export IOTRACE_INFLUX_ADMIN_USER="admin"
export IOTRACE_INFLUX_PASSWORD="test12345678"


./influx setup --bucket ${IOTRACE_INFLUX_BUCKET} -t ${IOTRACE_INFLUX_TOKEN} -o ${IOTRACE_INFLUX_ORGANIZATION} --username=${IOTRACE_INFLUX_ADMIN_USER} --password=${IOTRACE_INFLUX_PASSWORD} -f