version: '3'
services:
        prometheus:
                image: 'prom/prometheus'
                volumes:
                        - './prometheus.yml:/etc/prometheus/prometheus.yml'
                ports:
                        - "9090:9090"
        push-gateway:
                image: 'prom/pushgateway'
                ports:
                        - "9091:9091"
        grafana:
                image: 'grafana/grafana'
                ports:
                        - "3000:3000"
        node-exporter:
                image: 'prom/node-exporter'
                ports:
                        - "9100:9100"
