#ifndef LIBIOTRACE_STRACER_H
#define LIBIOTRACE_STRACER_H


/* - CLI flags - */
#define STRACER_CLI_OPTION_SOCKFD  's'
#define STRACER_CLI_OPTION_SSUBSET 'e'
#define STRACER_CLI_OPTION_WARN    'w'


#endif /* LIBIOTRACE_STRACER_H */
