#ifndef LIBIOTRACE_STRACER_CONSTS_H
#define LIBIOTRACE_STRACER_CONSTS_H


/* -- Consts -- */
/* - CLI - */
#define STRACER_CLI_OPTION_SOCKFD             's'
#define STRACER_CLI_OPTION_SSUBSET            'e'

#define STRACER_CLI_OPTION_LIBIOTRACE_LINKAGE 'l'
#define STRACER_CLI_LIBIOTRACE_LINKAGE_STATIC 's'
#define STRACER_CLI_LIBIOTRACE_LINKAGE_SHARED 'd'

#define STRACER_CLI_OPTION_TASK_WARN          'w'
#define STRACER_CLI_OPTION_TASK_FNRES         'f'


/* - Misc. - */
#define STRACING_FNRES_SMO_NAME_FORMAT        "_STRACING__tid_%ld"


#endif /* LIBIOTRACE_STRACER_CONSTS_H */
