{
 "title": "Dynamic-Drill-Down",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "measurement",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"_measurement\",\r\n  predicate: (r) => true,\r\n  start: -100d\r\n)"
   },
   {
    "name": "hostname",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"hostname\",\r\n  predicate: (r) => r._measurement == \"${measurement}\",\r\n  start: -100d,\r\n)"
   },
   {
    "name": "jobname",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"jobname\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\",\r\n  start: -100d\r\n)"
   },
   {
    "name": "processid",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"processid\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\",\r\n  start: -100d\r\n)"
   },
   {
    "name": "thread",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"thread\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r.processid == \"${processid}\",\r\n  start: -100d\r\n)"
   },
   {
    "name": "functionname",
    "label": "function",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"functionname\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r.processid == \"${processid}\" and r.thread == \"${thread}\",\r\n  start: -100d\r\n)"
   },
   {
    "name": "field",
    "query": "time_diff, function_data_written_bytes, function_data_read_bytes"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All processes in time frame",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"${field}\" and r.functionname !~ /.*_std_.*/)\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Dynamic Drill Down - $field", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "All hosts",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"${field}\" and r.functionname !~ /.*_std_.*/)\r\n  |> group(columns: [\"hostname\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Processes of host $hostname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"${field}\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Threads of process $processid",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"${field}\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\" and r.processid == \"${processid}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\", \"thread\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Functions of thread $thread",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"${field}\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\" and r.processid == \"${processid}\" and r.jobname == \"${jobname}\" and r.thread == \"${thread}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\", \"thread\", \"functionname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Files used by function $functionname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"${field}\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\" and r.processid == \"${processid}\" and r.jobname == \"${jobname}\" and r.thread == \"${thread}\" and r.functionname == \"${functionname}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\", \"thread\", \"functionname\", \"filename\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Time only Drill Down",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time used by hosts",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"time_diff\" and r.functionname !~ /.*_std_.*/)\r\n  |> group(columns: [\"hostname\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Time used by processes of host $hostname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"time_diff\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Time used by threads of process $processid",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"time_diff\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\" and r.processid == \"${processid}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\", \"thread\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Time used by functions of thread $thread",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"time_diff\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\" and r.processid == \"${processid}\" and r.jobname == \"${jobname}\" and r.thread == \"${thread}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\", \"thread\", \"functionname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Time used for files of function $functionname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"time_diff\" and r.functionname !~ /.*_std_.*/)\r\n  |> filter(fn: (r) => r.hostname == \"${hostname}\" and r.processid == \"${processid}\" and r.jobname == \"${jobname}\" and r.thread == \"${thread}\" and r.functionname == \"${functionname}\")\r\n  |> group(columns: [\"hostname\", \"jobname\", \"processid\", \"_field\", \"thread\", \"functionname\", \"filename\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}