{
 "title": "File-Access-Analysis",
 "time": { "from": "2024-04-04T12:00:17.785Z", "to": "2024-04-04T12:03:34.817Z" },
 "templating": {
  "list": [
   { "name": "bucket", "label": "Bucket", "query": "buckets()" },
   {
    "name": "measurement",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"_measurement\",\r\n  predicate: (r) => true,\r\n  start: -1000d\r\n)"
   },
   {
    "name": "jobname",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"jobname\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\",\r\n  start: -1000d\r\n)"
   },
   {
    "name": "hostname",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"hostname\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\",\r\n  start: -1000d,\r\n)"
   },
   {
    "name": "filename",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"traced_filename\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r._field == \"cursor_position\",\r\n  start: -1000d\r\n)"
   },
   {
    "name": "function_data_id_device_id",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"function_data_id_device_id\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\",\r\n  start: -1000d\r\n)"
   },
   {
    "name": "function_data_id_inode_nr",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"function_data_id_inode_nr\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\",\r\n  start: -1000d\r\n)"
   },
   {
    "name": "file_access_identifier",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"file_access_identifier\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\",\r\n  start: -1000d\r\n)"
   },
   {
    "name": "processid",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"pid\",\r\n  predicate: (r) => r._measurement == \"${measurement}\" and r.hostname == \"${hostname}\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\",\r\n  start: -1000d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Optimizations Pie Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Optimizations per file",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\" and r._field == \"category\")\r\n  |> filter(fn: (r) => r.category == \"1\" or r.category == \"2\")\r\n  |> group(columns: [\"hostname\", \"traced_filename\", \"function_data_id_device_id\", \"function_data_id_inode_nr\"])\r\n  |> count()\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Select FAID of file $filename",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\" and r.hostname == \"${hostname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r._field == \"category\")\r\n  |> filter(fn: (r) => r.category == \"1\" or r.category == \"2\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> count()\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  { "title": "Optimizations Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Possible optimizations per file (click to select)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\" and r._field == \"category\")\r\n  |> filter(fn: (r) => r.category == \"1\" or r.category == \"2\")\r\n  |> group(columns: [\"hostname\", \"traced_filename\", \"function_data_id_device_id\", \"function_data_id_inode_nr\"])\r\n  |> count()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Possible optimizations of file_access_identifiers of file $filename (click to select)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\" and r.hostname == \"${hostname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r._field == \"category\")\r\n  |> filter(fn: (r) => r.category == \"1\" or r.category == \"2\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> count()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Optimization Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cursor Offset of stream $file_access_identifier in file $filename compared with other streams important access times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier == \"${file_access_identifier}\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"function_name\"], valueColumn: \"_value\")\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "maxValue = from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier == \"${file_access_identifier}\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> max()\r\n  |> findRecord(fn: (key) => true, idx: 0)\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier != \"${file_access_identifier}\")\r\n  |> group(columns: [\"jobname\"])\r\n  |> map(fn: (r) => ({r with _value: if r._value > 0 then maxValue._value else 0}))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"function_name\"], valueColumn: \"_value\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Possible optimizations of FAID $file_access_identifier",
   "type": "timeseries",
   "description": "Colorcoding of points (category): red - can't be optimized (0), green - can be optimized (1/2), orange - not defined (3)\n\nHover point for details.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"category\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier == \"${file_access_identifier}\")\r\n  |> group(columns: [\"category\", \"info\", \"function\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"category\"], valueColumn: \"_value\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Detailed Job Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "All file access IDs of file $filename",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\")\r\n  |> group(columns: [\"traced_filename\",\"file_access_identifier\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Select file of job $jobname",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\" and r._field == \"cursor_position\")\r\n  |> group(columns: [\"hostname\", \"traced_filename\", \"function_data_id_device_id\", \"function_data_id_inode_nr\"])\r\n  |> count()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cursor Offset of FAID $file_access_identifier split in functions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier == \"${file_access_identifier}\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"function_name\"], valueColumn: \"_value\")\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Select FAID of file $filename",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r._field == \"cursor_position\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> count()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Cursor Offset of stream $file_access_identifier in file $filename compared with other streams important access times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier == \"${file_access_identifier}\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"function_name\"], valueColumn: \"_value\")\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "maxValue = from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier == \"${file_access_identifier}\")\r\n  |> group(columns: [\"file_access_identifier\"])\r\n  |> max()\r\n  |> findRecord(fn: (key) => true, idx: 0)\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r._field == \"cursor_position\" and r.jobname == \"${jobname}\" and r.traced_filename == \"${filename}\" and r.function_data_id_device_id == \"${function_data_id_device_id}\" and r.function_data_id_inode_nr == \"${function_data_id_inode_nr}\" and r.file_access_identifier != \"${file_access_identifier}\")\r\n  |> group(columns: [\"jobname\"])\r\n  |> map(fn: (r) => ({r with _value: if r._value > 0 then maxValue._value else 0}))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"function_name\"], valueColumn: \"_value\")\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}