{
 "title": "libiotrace2",
 "time": { "from": "2024-06-06T21:29:20.573Z", "to": "2024-06-06T21:29:20.685Z" },
 "templating": {
  "list": [
   {
    "name": "jobname",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"jobname\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\",\r\n  start: -100d\r\n)"
   },
   {
    "name": "ProzessID",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"processid\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\" and r[\"jobname\"] == \"${jobname}\",\r\n  start: -100d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "MPI Variable Visuals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "MPI-Prozesse für Job: $jobname",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\" and r.functionname =~ /.*MPI.*/)\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid}))\r\n  |> distinct(column: \"Prozess ID\")\r\n  |> map(fn: (r) => ({\"Prozesse\": r._value}))"
      }
     ]
    },
    {
     "title": "Dauer einzelner Seek & Write Funktionen Prozess $ProzessID",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "repeat": "ProzessID",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"${ProzessID}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\r\n  \r\n "
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process ${ProzessID}",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\n  |> filter(fn: (r) => r[\"processid\"] == \"${ProzessID}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MPI Read Parallel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "MPI Seek Offset ",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_parallel_iread_export\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"4044\" or r[\"processid\"] == \"4045\" or r[\"processid\"] == \"4046\" or r[\"processid\"] == \"4047\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\")\r\n  |> map(fn: (r) => ({Datei: r.filename, \"Prozess ID\": r. processid, Offset: r._value, Funktion: r.functionname}))\r\n\r\n"
      }
     ]
    },
    {
     "title": "Durchschnittliche Zeit aller Prozesse in MPI-Funktionen",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_parallel_iread_export\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"4044\" or r[\"processid\"] == \"4045\" or r[\"processid\"] == \"4046\" or r[\"processid\"] == \"4047\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_Wait\" or r[\"functionname\"] == \"MPI_File_iread\" or r[\"functionname\"] == \"MPI_File_close\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid, \"Zeit in ns\": r._value, Funktion: r.functionname, Datei: r.filename }))\r\n  |> group(columns: [\"Funktion\"])\r\n  |> mean(column: \"Zeit in ns\")\r\n  |> group()"
      }
     ]
    },
    {
     "title": "Function Runtime Process 4044",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_parallel_iread_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4044\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_Wait\" or r[\"functionname\"] == \"MPI_File_iread\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Function Runtime Process 4045",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_parallel_iread_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4045\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_Wait\" or r[\"functionname\"] == \"MPI_File_iread\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Function Runtime Process 4046",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_parallel_iread_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4046\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_Wait\" or r[\"functionname\"] == \"MPI_File_iread\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Function Runtime Process 4047",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_parallel_iread_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4047\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_Wait\" or r[\"functionname\"] == \"MPI_File_iread\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MPI File IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Offset der Prozesse bei MPI Seek",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_export\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"4656\" or r[\"processid\"] == \"4657\" or r[\"processid\"] == \"4658\" or r[\"processid\"] == \"4659\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\")\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid, Offset: r._value}))\r\n  |> group()\r\n  |> sort(columns: [\"Offset\"], desc: false)"
      }
     ]
    },
    {
     "title": "Dauer einzelner Seek & Write Funktionen Prozess 4656",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_export\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"4656\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\r\n  \r\n "
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 4656",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4656\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 4657",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4657\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 4658",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4658\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 4659",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_export\")\n  |> filter(fn: (r) => r[\"processid\"] == \"4659\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MPI File IO 1k Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offset der Prozesse bei MPI Seek",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"5094\" or r[\"processid\"] == \"5095\" or r[\"processid\"] == \"5096\" or r[\"processid\"] == \"5097\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\")\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid, Offset: r._value}))\r\n  |> group()\r\n  |> sort(columns: [\"Offset\"], desc: false)"
      }
     ]
    },
    {
     "title": "Dauer einzelner Seek & Write Funktionen Prozess 5094",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"5094\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\r\n  \r\n "
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 5094",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k\")\n  |> filter(fn: (r) => r[\"processid\"] == \"5094\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 5095",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k\")\n  |> filter(fn: (r) => r[\"processid\"] == \"5095\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 5096",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k\")\n  |> filter(fn: (r) => r[\"processid\"] == \"5096\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 4658",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k\")\n  |> filter(fn: (r) => r[\"processid\"] == \"5096\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MPI File IO 1k Updated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Offset der Prozesse bei MPI Seek",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"10241\" or r[\"processid\"] == \"10242\" or r[\"processid\"] == \"10244\" or r[\"processid\"] == \"10246\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\")\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid, Offset: r._value}))\r\n  |> group()\r\n  |> sort(columns: [\"Offset\"], desc: false)"
      }
     ]
    },
    {
     "title": "Dauer einzelner Seek & Write Funktionen Prozess 10241",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"10241\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\r\n  \r\n "
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 10241",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\n  |> filter(fn: (r) => r[\"processid\"] == \"10241\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 10242",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\n  |> filter(fn: (r) => r[\"processid\"] == \"10242\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 10244",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\n  |> filter(fn: (r) => r[\"processid\"] == \"10244\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Summed up Function Runtime Process 10246",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\n  |> filter(fn: (r) => r[\"processid\"] == \"10246\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_open\" or r[\"functionname\"] == \"MPI_File_seek\" or r[\"functionname\"] == \"MPI_File_write\" or r[\"functionname\"] == \"MPI_File_close\")\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MPI_File_IO Timeline Seek&Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Seek&Write Realtime for $jobname",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: 2024-05-19T07:22:25.56Z, stop: 2024-06-18T07:22:25.561Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"10241\" or r[\"processid\"] == \"10242\" or r[\"processid\"] == \"10244\" or r[\"processid\"] == \"10246\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_written_bytes\") //or r[\"_field\"] == \"function_data_written_bytes\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\", \"_start\", \"_stop\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_write\")\r\n  |> map(fn:(r) => ({r with \"_value\": int(v: r[\"_value\"])}))\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> drop(columns: [\"_field\", \"filename\",\"functionname\", \"thread\"])\r\n  |> rename(columns: {_time: \"Zeit\", _value: \"Bytes\"})\r\n  "
    },
    {
     "query": "\r\nfrom(bucket: \"hsebucket\")\r\n  |> range(start: 2024-05-19T07:22:25.56Z, stop: 2024-06-18T07:22:25.561Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"mpi_file_io_1k_updated\")\r\n  |> filter(fn: (r) => r[\"processid\"] == \"10241\" or r[\"processid\"] == \"10242\" or r[\"processid\"] == \"10244\" or r[\"processid\"] == \"10246\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\") //or r[\"_field\"] == \"function_data_written_bytes\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\", \"_start\", \"_stop\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\")\r\n  |> map(fn:(r) => ({r with \"_value\": int(v: r[\"_value\"])}))\r\n  |> group()\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> drop(columns: [\"_field\", \"filename\",\"functionname\", \"thread\"])\r\n  |> rename(columns: {_time: \"Zeit\", _value: \"Offset\"})\r\n  "
    }
   ]
  }
 ]
}