{
 "title": "Thread Map & Drilldown",
 "time": { "from": "2023-02-22T10:00:00.000Z", "to": "2023-02-22T16:59:59.000Z" },
 "panels": [
  { "title": "ThreadMap & Drilldown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ThreadMap",
   "type": "hse-testpluginsr-panel",
   "description": "Anzeige von Prozessen und deren Threads\n(inkl. Auslastung)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"hsebucket_fileres\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_read_bytes\" or r[\"_field\"] == \"function_data_written_bytes\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"fread\" or r[\"functionname\"] == \"fwrite\" or r[\"functionname\"] == \"read\" or r[\"functionname\"] == \"write\" or r[\"functionname\"] == \"writev\")\r\n  |> group(columns: [\"thread\", \"processid\"])\r\n  |> aggregateWindow(every: inf, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    },
    {
     "query": "from(bucket: \"hsebucket_fileres\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"fread\" or r[\"functionname\"] == \"fwrite\" or r[\"functionname\"] == \"read\" or r[\"functionname\"] == \"write\" or r[\"functionname\"] == \"writev\")\r\n  |> group(columns: [\"thread\", \"processid\"])\r\n  |> aggregateWindow(every: inf, column:\"_value\", fn:distinct, createEmpty: false)\r\n  |>yield(name: \"distinct\")"
    }
   ]
  },
  {
   "title": "Filename Write",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "  from(bucket: \"hsebucket_fileres\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"traced_filename\")\r\n    |> filter(fn: (r) => r[\"functionname\"] == \"fwrite\" or r[\"functionname\"] == \"write\" or r[\"functionname\"] == \"writev\")\r\n    |> keep(columns: [\"thread\", \"processid\", \"_value\"])\r\n    |> distinct()\r\n    |> map(fn: (r) => ({ r with TracedFilenameWrite: r._value}))\r\n    |> drop(columns: [\"_value\"])\r\n    |> yield(name: \"q1\")\r\n"
    }
   ]
  },
  {
   "title": "Filename Read",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"hsebucket_fileres\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"traced_filename\")\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"fread\" or r[\"functionname\"] == \"read\")\r\n  |> keep(columns: [\"thread\", \"processid\", \"_value\"])\r\n  |> distinct()\r\n  |> map(fn: (r) => ({ r with TracedFilenameRead: r._value}))\r\n  |> drop(columns: [\"_value\"])\r\n  |> yield(name: \"q2\")"
    }
   ]
  },
  {
   "title": "Drill Down Force Graph",
   "type": "hs-esslingen-force-graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"hsebucket_fileres\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"function_data_written_bytes\")\r\n|> filter(fn: (r) => r[\"functionname\"] == \"fwrite\" or r[\"functionname\"] == \"writev\" or r[\"functionname\"] == \"write\")\r\n|> group(columns: [\"thread\", \"processid\"])\r\n|> aggregateWindow(every: inf, fn: sum, createEmpty: false)\r\n|> yield(name: \"sum\")"
    },
    {
     "query": "from(bucket: \"hsebucket_fileres\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"traced_filename\")\r\n|> filter(fn: (r) => r[\"functionname\"] == \"fwrite\" or r[\"functionname\"] == \"writev\" or r[\"functionname\"] == \"write\")\r\n|> group(columns: [\"thread\", \"processid\"])\r\n|> aggregateWindow(every: inf, column:\"_value\", fn:distinct, createEmpty: false)\r\n|>yield(name: \"distinct\")"
    }
   ]
  }
 ]
}