{
 "title": "Visualisierung von MPI-File-I/O",
 "description": "Panel für das 2. Semester des Forschungsprojekts",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobname",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"jobname\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\",\r\n)\r\n"
    }
   },
   {
    "name": "ProzessID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"processid\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\" and r[\"jobname\"] == \"${jobname}\",\r\n)"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"hostname\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\" and r[\"jobname\"] == \"${jobname}\",\r\n)\r\n"
    }
   },
   {
    "name": "functionname",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"functionname\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\" and \r\n            r[\"jobname\"] == \"${jobname}\" and r[\"functionname\"] =~ /.*MPI.*/ ,\r\n)\r\n"
    }
   },
   {
    "name": "filename",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"hsebucket\",\r\n  tag: \"filename\",\r\n  predicate: (r) => r[\"_measurement\"] == \"libiotrace\" and \r\n            r[\"jobname\"] == \"${jobname}\" and r[\"functionname\"] =~ /.*MPI.*/ ,\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Allgemeine Job Informationen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Summed up Function Runtime Process ${ProzessID}",
     "type": "barchart",
     "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
     "repeat": "ProzessID",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\n  |> filter(fn: (r) => r[\"processid\"] == \"${ProzessID}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Auflistung Prozesse und Hosts",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\" and r.functionname =~ /.*MPI.*/)\r\n  |> map(fn: (r) => ({\"Prozess_ID\": r. processid, \"name\": r.hostname}))\r\n  |> group(columns: [\"Prozess_ID\", \"name\"], mode:\"by\")\r\n  |> distinct(column: \"Prozess_ID\")\r\n  |> map(fn: (r) => ({\"Prozess ID\": r.Prozess_ID, \"Hostname\": r.name}))"
      }
     ]
    },
    {
     "title": "Auflistung Prozesse und Hosts",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "prozesse = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\" and r.functionname =~ /.*MPI.*/)\r\n  |> map(fn: (r) => ({\"Prozesse\": r. processid, \"Hosts\": r.hostname}))\r\n  |> distinct(column: \"Prozesse\")\r\n  |> count(column: \"_value\")\r\n  |> rename(columns: {_value: \"Anzahl Prozesse\"})\r\n\r\n\r\nhosts = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\" and r.functionname =~ /.*MPI.*/)\r\n  |> map(fn: (r) => ({\"Prozesse\": r. processid, \"Hosts\": r.hostname}))\r\n  |> distinct(column: \"Hosts\")\r\n  |> count(column: \"_value\")\r\n  |> rename(columns: {_value: \"Anzahl Hosts\"})\r\n\r\n\r\nunion(tables: [hosts, prozesse]) // Kombiniere beide Tabellen\r\n|> yield(name: \"combined\")"
      }
     ]
    },
    {
     "title": "Erste und letzte ausgeführte MPI Funktion von Prozess $ProzessID",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "query": "mpitime = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_start\" or r[\"_field\"] == \"time_end\")\r\n  |> group(columns: [\"time\"], mode:\"by\")  \r\n  |> sort()\r\n  firstEntry = mpitime |> first() // Hole den ersten Eintrag\r\n  lastEntry = mpitime |> last()   // Hole den letzten Eintrag\r\n  \r\nunion(tables: [firstEntry, lastEntry]) // Kombiniere beide Tabellen\r\n  |> map(fn: (r) => ({\"_value\": r._value , \"Funktion\" : r.functionname }))\r\n  |> toTime()\r\n  |> rename (columns: {_value: \"Zeitstempel\"})\r\n  |> yield(name: \"mpitime\")\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Betrachtung der Funktionen innerhalb eines Prozesses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prozess $ProzessID: Durchschnittliche Laufzeit von Funktion: $functionname",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 241 },
     "repeat": "ProzessID",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({\"_value\": r._value , \"Funktion\" : r.functionname }))\r\n  |> group(columns: [\"Funktion\"])\r\n  |> mean()\r\n  |> rename(columns: {_value: \"Laufzeit\"})\r\n  |> yield()\r\n"
      }
     ]
    },
    {
     "title": "Prozess $ProzessID: Maximale Laufzeit von Funktion: $functionname",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 344 },
     "repeat": "ProzessID",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({\"_value\": r._value , \"Funktion\" : r.functionname }))\r\n  |> group(columns: [\"Funktion\"])\r\n  |> max()\r\n  |> rename(columns: {_value: \"Laufzeit\"})\r\n  |> yield()"
      }
     ]
    },
    {
     "title": "Prozess $ProzessID: Minimale Laufzeit von Funktion: $functionname",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 352 },
     "repeat": "ProzessID",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({\"_value\": r._value , \"Funktion\" : r.functionname }))\r\n  |> group(columns: [\"Funktion\"])\r\n  |> min()\r\n  |> rename(columns: {_value: \"Laufzeit\"})\r\n  |> yield()\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Prozessübergreifende Informationen zu MPI-Funktionen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prozess $ProzessID: Summierte Zeit in MPI-Funktionen",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: \"hsebucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\n  |> filter(fn: (r) => r[\"_field\"] == \"function_name\" or r[\"_field\"] == \"time_diff\" or r[\"_field\"] == \"traced_filename\")\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) => ({Zeit: r._value, Funktion: r.functionname }))\n  |> group(columns: [\"Funktion\"]) \n  |> sum(column: \"Zeit\") \n  |>group()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Durchschnittliche Zeit in MPI-Funktionen von Prozess $ProzessID",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: ${functionname:json}))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid, \"Zeit in ns\": r._value, Funktion: r.functionname, Datei: r.filename }))\r\n  |> group(columns: [\"Funktion\"])\r\n  |> mean(column: \"Zeit in ns\")\r\n  |> group()"
      }
     ]
    },
    {
     "title": "Return Code Übersicht für MPI Funktion $functionname",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 250 },
     "repeat": "functionname",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "ok = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"return_state\")\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"${functionname:json}\"]))\r\n  |> filter(fn: (r) => r[\"_value\"] == \"ok\")\r\n  |> map(fn: (r) => ({\"_value\": r._value}))\r\n  |> count()\r\n  |> rename(columns: {_value: \"ok\"})\r\n  |> yield(name: \"ok\")\r\n\r\n"
      },
      {
       "query": " notok = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"return_state\")\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"${functionname:json}\"]))\r\n  |> filter(fn: (r) => not r[\"_value\"] == \"ok\")\r\n  |> map(fn: (r) => ({\"_value\": r._value}))\r\n  |> count()\r\n  |> rename(columns: {_value: \"not ok\"})\r\n  |> yield(name: \"notok\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Graph einzelner MPI-Funktionen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "Node Graph for $functionname und File: $filename",
   "type": "nodeGraph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "repeat": "functionname",
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nsingle = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"${functionname:json}\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({mainstat: r._value, tmptitle: r.functionname, secondarystat: r.hostname, prozess: r.processid }))\r\n  |> group(columns: [\"tmptitle\"]) \r\n  |> sort(columns: [\"_time\"]) \r\n  |> map(fn: (r) => ({r with counter: 1})) // Assign 1 to each row\r\n  |> cumulativeSum(columns: [\"counter\"]) // Compute sequential identifiers\r\n  |> map(fn: (r) => ({ r with id: r.tmptitle + \":\" + string(v: r.counter)}))\r\n  |> map(fn: (r) => ({ r with title: r.tmptitle + \":\" + r.prozess}))\r\n  |> drop(columns: [\"counter\",\"prozess\",\"tmptitle\"])\r\n  |> map(fn: (r) => ({ r with key: \"const\" }))\r\n\r\ncumulativeNode = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"${functionname:json}\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({mainstat: r._value, title: r.functionname, prozess: r.processid, secondarystat: r.hostname }))\r\n  |> group(columns: [\"title\"])\r\n  |> sum(column: \"mainstat\")\r\n  |> limit(n: 1)\r\n  |> map(fn: (r) => ({ key: \"const\", MaxVal: r.mainstat }))\r\n  \r\npercent = join( tables: {const: cumulativeNode, data: single},on: [\"key\"], method: \"inner\")\r\n  |> map(fn: (r) => ({r with arc__percentage: if float(v:r.MaxVal) != 0.0 then math.round(x: (float(v: r.mainstat) / float(v: r.MaxVal)) * 100.0) / 100.0 else 0.0}))\r\n\r\n\r\nmainNode = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"${functionname:json}\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({mainstat: r._value, title: r.functionname, prozess: r.processid, secondarystat: r.hostname }))\r\n  |> group(columns: [\"title\"])\r\n  |> sum(column: \"mainstat\")\r\n  |> group()\r\n  |> map(fn: (r) => ({r with id: 1})) // Assign 1 to each row\r\n  |> cumulativeSum(columns: [\"id\"]) // Compute sequential identifiers\r\n  |> map(fn: (r) => ({ r with id: r.title}))\r\n  |> map(fn: (r) => ({ r with secondarystat: \"FA-Test\"}))\r\n  |> map(fn: (r) => ({ r with arc__percentage: 1.0}))\r\n\r\n final = union(tables: [percent, mainNode])\r\n  |> drop(columns: [\"key\",\"MaxVal\"])\r\n  |> yield(name: \"final\")"
    },
    {
     "query": "import \"strings\"\r\n\r\nedges = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"${functionname:json}\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"time_diff\")\r\n  |> map(fn: (r) => ({mainstat: r._value, tmpsource: r.functionname, secondarystat: r.hostname}))\r\n  |> group(columns: [\"tmpsource\"]) \r\n  |> sort(columns: [\"_time\"]) \r\n  |> map(fn: (r) => ({r with counter: 1}))\r\n  |> cumulativeSum(columns: [\"counter\"])\r\n  |> map(fn: (r) => ({ r with source: r.tmpsource + \":\" + string(v: r.counter)}))\r\n  |> map(fn: (r) => ({ r with id: \"edge:\" + r.source}))\r\n  |> drop(columns: [\"counter\",\"tmpsource\"])\r\n  |> map(fn: (r) => ({ r with color: \"blue\"}))\r\n  |> map(fn: (r) => {\r\n    parts = strings.split(v: r.source, t: \":\")\r\n    return {id: r[\"id\"],source: r[\"source\"],mainstat: r[\"mainstat\"],color: r[\"color\"],secondarystat: r[\"secondarystat\"],target: string(v: parts[0])}\r\n  })\r\n  |> yield(name: \"edges\")"
    }
   ]
  },
  {
   "title": "File-I/O Übersicht",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zeitreihe für File: $filename mit MPI-Write/Read/Seek",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 75 },
     "repeat": "filename",
     "targets": [
      {
       "query": "writtenbytes = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"MPI_File_write\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_written_bytes\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\", \"_start\", \"_stop\", \"filename\", \"thread\",\"_field\",\"functionname\"])\r\n  |> map(fn:(r) => ({r with \"_value\": int(v: r[\"_value\"])}))\r\n  |> rename(columns: {_time: \"Zeit\", _value: \"Bytes written\", processid: \"Prozess\"})\r\n  |> yield(name: \"writtenbytes\")\r\n  "
      },
      {
       "query": "ersterEintrag = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"MPI_File_seek\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\", \"_start\", \"_stop\", \"filename\", \"thread\",\"_field\",\"functionname\"])\r\n  |> map(fn:(r) => ({r with \"_value\": int(v: r[\"_value\"])}))\r\n  |> rename(columns: {_time: \"Zeit\", _value: \"Offset\", processid: \"Prozess\"})\r\n  |> sort(columns: [\"Zeit\"], desc: false)\r\n  |> limit(n: 1)\r\n\r\noffsetNoDubs = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}])) \r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"MPI_File_seek\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\", \"_start\", \"_stop\", \"filename\", \"thread\",\"_field\",\"functionname\"])\r\n  |> map(fn:(r) => ({r with \"_value\": int(v: r[\"_value\"])}))\r\n  |> rename(columns: {_time: \"Zeit\", _value: \"Offset\", processid: \"Prozess\"})\r\n  |> sort(columns: [\"Zeit\"], desc: false)\r\n  |> elapsed(timeColumn: \"Zeit\", unit: 1ns, columnName: \"elapsed\")\r\n  |> map(fn: (r) => ({r with adjustment: if exists r.elapsed and r.elapsed < 1000000 then 1000000 else 0}))\r\n  |> map(fn: (r) => ({r with neue_Zeit: int(v:r.Zeit) + int(v: r.adjustment) }))\r\n  |> map(fn: (r) => ({r with neue_Zeit: time(v: r.neue_Zeit)}))\r\n  |> drop(columns: [\"Zeit\",\"elapsed\",\"adjustment\"])\r\n  |> rename(columns: {neue_Zeit: \"Zeit\"})\r\n\r\nunion(tables: [ersterEintrag, offsetNoDubs])\r\n  |> yield(name: \"final\")"
      },
      {
       "query": "readbytes = from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"functionname\"], set: [\"MPI_File_read\"]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_read_bytes\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\", \"_start\", \"_stop\", \"filename\", \"thread\",\"_field\",\"functionname\"])\r\n  |> map(fn:(r) => ({r with \"_value\": int(v: r[\"_value\"]) * -1}))\r\n  |> rename(columns: {_time: \"Zeit\", _value: \"Bytes read\", processid: \"Prozess\"})\r\n  |> yield(name: \"readbytes\")"
      }
     ]
    },
    {
     "title": "Offset der Prozesse bei MPI Seek für File: $filename",
     "type": "barchart",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"hsebucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"libiotrace\")\r\n  |> filter(fn: (r) => r[\"jobname\"] == \"${jobname}\")\r\n  |> filter(fn: (r) => contains(value: r[\"filename\"], set: [${filename:doublequote}]))\r\n  |> filter(fn: (r) => contains(value: r[\"processid\"], set: [${ProzessID:doublequote}]))\r\n  |> filter(fn: (r) => r[\"_field\"] == \"function_data_offset\")\r\n  |> drop(columns: [\"_measurement\", \"hostname\", \"jobname\",\"_start\", \"_stop\", \"_time\"])\r\n  |> filter(fn: (r) => r[\"functionname\"] == \"MPI_File_seek\")\r\n  |> map(fn: (r) => ({\"Prozess ID\": r. processid, Offset: r._value}))\r\n  |> group()\r\n  |> sort(columns: [\"Offset\"], desc: false)"
      }
     ]
    }
   ]
  }
 ]
}